name: build and deploy
on:
  push:
    paths:
      - "*.tex"
      - "*.bib"
      - "*.cls"
      - "*.bbx"
      - "*.cbx"
      # Always run when the actions change!
      - ".github/workflows/*.yml"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Git repo
        uses: actions/checkout@v4
      - name: First LaTeX run
        uses: dante-ev/latex-action@latest
        with:
          args: ""
          root_file: cv.tex
      - name: Biber run
        uses: dante-ev/latex-action@latest
        with:
          compiler: biber
          # No extra args
          args: ""
      - name: Second LaTeX run
        uses: dante-ev/latex-action@latest
        with: 
          args: -lualatex -latexoption=-file-line-error -latexoption=-interaction=nonstopmode
          # Remember that we don't run `biber cv.tex' but `biber cv'
          root_file: cv
      - name: Last LaTeX run
        uses: dante-ev/latex-action@latest
        with: 
          args: -lualatex -latexoption=-file-line-error -latexoption=-interaction=nonstopmode
          root_file: cv.TeX
      - name: Upload output pdf as artefact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'cv.pdf'  
  deploy:
    needs: build
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v4