name: build and deploy
on:
  push:
    paths:
      - "*.tex"
      - "*.bib"
      - "*.cls"
      - "*.bbx"
      - "*.cbx"
      # Always run when the actions change!
      - ".github/workflows/*.yml"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Git repo
        uses: actions/checkout@v4
      - name: Setup TeX Live
        uses: teatimeguest/setup-texlive-action@v3
        with:
          packages: |
            scheme-basic
            orcidlink
            hyperref
      - name: First LaTeX run
        run: 'lualatex cv.tex'
      - name: Biber run
        run: 'biber cv'
      - name: Second LaTeX run
        run: 'lualatex cv.tex'
      - name: Final LaTeX run
        run: 'lualatex cv.tex'
      - name: Upload output pdf as artefact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'cv.pdf'  
  deploy:
    needs: build
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v4